### ISSUE TITLE
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'status_iterator'

### ISSUE THREAD

**Issue by danielvasas** [useblocks/sphinxcontrib-needs#42] opened 2018-03-14 15:12 UTC
Hello,

after latest update of my environment, and with that a couple of related packages, I'm getting this exception.

Sphinx version: 1.7.1
Python version: 3.6.2 (CPython)
Docutils version: 0.14
Jinja2 version: 2.10
Last messages:
reading sources... [ 89%] contents/doc_user/introduction/index
reading sources... [ 92%] contents/doc_user/quickstart/index
reading sources... [ 96%] contents/doc_user/usage/index
reading sources... [100%] index
Loaded extensions:
alabaster (0.7.10) from c:\dev\ve_safe_build_36\lib\site-packages\alabaster_init_.py
sphinx.ext.autodoc (1.7.1) from c:\dev\ve_safe_build_36\lib\site-packages\sphinx\ext\autodoc_init_.py
sphinxcontrib.plantuml (unknown version) from c:\dev\ve_safe_build_36\lib\site-packages\sphinxcontrib\plantuml.py
sphinxcontrib.needs (0.1.49) from c:\dev\ve_safe_build_36\lib\site-packages\sphinxcontrib\needs_init_.py
Traceback (most recent call last):
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\cmdline.py", line 304, in main
app.build(args.force_all, filenames)
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\application.py", line 331, in build
self.builder.build_update()
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\builders_init_.py", line 333, in build_update
'out of date' % len(to_build))
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\builders_init_.py", line 346, in build
updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\environment_init_.py", line 571, in update
for retval in self.app.emit('env-updated', self):
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\application.py", line 444, in emit
return self.events.emit(event, self, *args)
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\events.py", line 79, in emit
results.append(callback(*args))
File "c:\dev\ve_safe_build_36\lib\site-packages\sphinxcontrib\needs\environment.py", line 18, in install_backend_static_files
for source_file_path in app.builder.status_iterator(
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'status_iterator'

Here as comppelte pip list:

alabaster (0.7.10)
arrow (0.10.0)
Babel (2.5.3)
binaryornot (0.4.4)
blinker (1.4)
buildexecutor (1.2.0, c:\dev\ascgit307\ascgit307.buildexec)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
cmdb-common (2.2.0)
cmimporter (1.1.1, c:\dev\ascgit307\ascgit307.cmimporter)
cmtranslator (0.1.0)
colorama (0.3.9)
cookiecutter (1.6.0)
coverage (4.4.1)
docutils (0.14)
first (2.0.1)
flake8 (3.4.1)
future (0.16.0)
gitdb2 (2.0.2)
GitPython (2.1.5)
groundwork (0.1.12)
groundwork-database (0.1.3)
groundwork-sphinx-theme (1.0.8)
groundwork-validation (0.1.5)
gw-utils (0.2.2, c:\dev\ascgit307\ascgit307.gw_utils)
idna (2.6)
imagesize (1.0.0)
Jinja2 (2.10)
jinja2-time (0.2.0)
jsonschema (2.6.0)
komparator (1.1.0, c:\dev\ascgit307\ascgit307.komparator)
lxml (4.1.1)
MarkupSafe (1.0)
matrixchecker (0.1.1, c:\dev\ascgit307\ascgit307.matrix_checker)
mccabe (0.6.1)
packaging (17.1)
pathlib (1.0.1)
pip (9.0.1)
pip-tools (1.9.0)
pluggy (0.5.2)
poyo (0.4.1)
py (1.4.34)
pycodestyle (2.3.1)
pyelftools (0.24-st.1)
pyflakes (1.5.0)
Pygments (2.2.0)
pyparsing (2.2.0)
pytest (3.2.2)
pytest-cov (2.5.1)
pytest-runner (2.12.1)
python-dateutil (2.6.1)
pytz (2018.3)
PyYAML (3.12)
requests (2.18.4)
setuptools (38.5.2)
six (1.11.0)
smmap2 (2.0.3)
snowballstemmer (1.2.1)
Sphinx (1.7.1)
sphinxcontrib-needs (0.1.49)
sphinxcontrib-plantuml (0.10)
sphinxcontrib-websupport (1.0.1)
SQLAlchemy (1.1.14)
tox (2.8.2)
urllib3 (1.22)
vcversioner (2.16.0.0)
verifikator (0.2.1, c:\dev\ascgit307\ascgit307.verifikator)
virtualenv (15.1.0)
whichcraft (0.4.1)
yamldirs (1.1.3)

**Comment by danielvasas** [comment] 2018-03-14 15:12
The error disappears, if I revert these packages to this:

Sphinx (1.6.3)

sphinxcontrib-needs (0.1.47)

sphinxcontrib-plantuml (0.8.1)

**Comment by ubmarco** [comment] 2018-03-14 15:17
This is a duplicate of #41

**Closed** 2018-03-14 15:18 UTC
Labels: duplicate
