### ISSUE TITLE
Keep 'type_name' as css selector "<table class=$type_name ..."

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#124] opened 2020-02-03 15:18 UTC
In the new 0.5 layout/style options the need-name (or 'typename') is not available as class/ccs-selector anymore; unlike in/up-to the 0.4.3 version(s). 
Plz consider that as a "bug" and make it avalable again.

Background
I like "needs", and I do see benifits in the new layout/stye/grid options. However, I like to  to visuallizse the "kind of need" (slightly). 
Reqs are red, Specs are blue, and Tests are yellow. (We use subtle,  gradations for background -coler ; but you get the idea.)

In 043 that was simple to configure, WITOUT that "spec-writers" had to remember which 'style-option' to set. They coud, for special cases; but in general it was automagically correct.

Now, in 0.50, that isn't pssible anymore -- for my a reason to deinstall the latest version (Which I dont like)

Thanks

**Comment by ubmarco** [comment] 2020-02-03 15:30
There is a much more flexible solution to this, global options together with filter strings.
For this to work you need this in your conf.py:
```
needs_global_options = {
    'style': [
        ("[[copy('type')]]", "type in ['<your type>']"),
        ("[[copy('type')]]", "type in ['<your 2nd type>']"),
    ],
}
def setup(app):
    app.add_stylesheet('mystyle.css')
```
and then in `_static/mystyle.css`:
```
table.needs_style_<your type> tr.head td {
    background: lightgreen !important;
}
```

**Comment by ubmarco** [comment] 2020-02-03 15:34
Another note: with the new 0.5 version you also need to adapt your CSS selectors because needs is now based on tables for the new layout feature. This is much more flexible but also brings the downside of incompatible CSS selectors.

**Comment by danwos** [comment] 2020-02-03 16:16
Thanks for reporting this.

I think setting the style based on need-type is a very common use case.
Therefor I have reimplemented it.
The css-class name is ``needs_type_`` + need-typ (directive name!).
Example: ``needs_type_test`` for test cases, as the used directive is named ``test`` only.

It is not released yet. May happen in 2-3 days.
Will be part of [0.5.2](https://sphinxcontrib-needs.readthedocs.io/en/latest/changelog.html#not-released-yet).
So grab the last commit from master, if you want to test it.

@ubmarco: Thanks for providing and explaining the powerful alternative.

**Closed by danwos** 2020-02-03 16:16 UTC

**Comment by AlbertMietus** [comment] 2020-02-09 17:21
Just got the record: The  *global_option/copy()* option  has a (big) drawback:
Each and all needs (the visual table) has an **extra item listed** - may even be a double!

There are also some python bugs that prevent it working. Will try to report them. 

> *For now back to 042*

**Comment by danwos** [comment] 2020-02-10 05:15
Thanks for report,

yes please try to report the bugs with some code to reproduce, as I don't have the double and python bugs behavior in current projects.

The Css selector for need-types is back since 0.5.2. So no need to use the global_option anymore:

> Bugfix: Added need-type as css-class back on need. Css class name is needs_type_(need_type attribute). (#124)

BTW: If you don't want to have certain values in your need-output, you can [create your own layout ](https://sphinxcontrib-needs.readthedocs.io/en/latest/layout_styles.html#defining-own-layouts)to configure, which information shall be shown or shall be hidden.

**Comment by AlbertMietus** [comment] 2020-02-11 11:53
About the bugs (see above): 

They are (also) found+fixed in the current branch. Will not re-report them :-)
