### ISSUE TITLE
Sphinx-Needs affecting incremental behavior

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#343] opened 2021-07-31 06:58 UTC
I am running Sphinx with the (default) incremental behavior on. This means HTMLs shall be generated only for the changed rST files. If there are no changes, a sphinx-build shall return the following.

```
looking for now-outdated files... none found
no targets are out of date.
```
I recently noticed that all HTMLs were always generated, even if no changes are done. This means, the sphinx-build returns for example, 

```
building [html]: targets for x source files that are out of date
```
This makes the successive builds always slow as they are not incremental anymore.

I tried to remove the used third-party extensions one by one to nail down to the following.

If sphinx-needs is added as an extension and the `needs_extra_options` or `needs_functions` is initialized in `conf.py`, the incremental (write) behavior is turned off. Adding only the extension but no needs config as above in `conf.py` does not cause any problem. Also no rST file with a need object is required to cause the wrong behavior, just adding the above configs will rebuild all rST files always. 
*NOTE:* The read process is still incremental, but the write not anymore.

To reproduce the problem.

1. Create a `conf.py` with

```
extensions = ['sphinxcontrib.needs']

from docutils.parsers.rst import directives   
needs_extra_options = {
"my-option": directives.unchanged
}
```

2. Create a single rST file with any contents (no need object required)

3. Do a sphinx-build

4. Do a sphinx-build again

5. The HTML are always regenerated with newer timestamps.

The same problem happens with [sphinx-test-reports](https://sphinx-test-reports.readthedocs.io/en/latest/). In this case, just adding the extension to `conf.py` is enough to cause the problem.

```
extensions = ['sphinxcontrib.needs', 'sphinxcontrib.test_reports']
```

Tested with sphinx-needs 0.7.1 and sphinx 3.5.4/sphinx 4.1.1. Even 0.6.x versions of sphinx-needs have this problem I suppose as the incremental behavior was broken since long (or always broken).

**Comment by danwos** [comment] 2021-08-05 07:22
Wow, that's a strange behavior and I have no glue what causes this.
Need some time to setup a test environment and make some tests.
As of now Sphinx-Needs does not tell Sphinx to do a full "Write" operation or is anywhere else trying to configure the overall sphinx read/write process.
So this behavior must be caused by some spooky side-effect.

Thanks for already hunting this bug down to config vars, which are triggering this.

sphinx-test-reports sets some ``needs_extra_options`` automatically, so I think problem needs to be fixed in Sphinx-Needs only.

**Comment by twodrops** [comment] 2021-09-07 17:22
@danwos Any clue on this? In our case, this mostly affects the [reStructuredText VsCode Extension](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext), which tries to incrementally generate the HTML for the rST being previewed. Because it is not incremental anymore, the preview takes close to 2 minutes to show up :(

**Comment by danwos** [comment] 2021-09-08 14:53
I can reproduce the problem, but I have no idea how this behavior can happen.

Its really strange, as ``needs_extra_options`` gets always some values from internal code (even if not used in conf.py).
So ``needs_extra_options`` is always set, but deactivates incremental-build only, if also used in conf.py.

I have deactivated most code which deals with ``needs_extra_option``, but not effect.

BTW: ``needs_extra_option`` forces Sphinx to rewrite the output of each file only.
Reading and generating the content seems not be affected.

However, I asked the Sphinx-Dev-Group for help. Maybe they can give some hints:
https://groups.google.com/u/1/g/sphinx-dev/c/rR8l3jVh00A

**Comment by twodrops** [comment] 2021-09-08 15:59
@danwos Thanks for checking this again.

> BTW: needs_extra_option forces Sphinx to rewrite the output of each file only.
Reading and generating the content seems not be affected.

Didn't not quite get what you meant by this. I realized that `needs_extra_option` affects the incremental behavior of write only and not the read. I did not understand what you meant by "generating the content seems not be affected"

**Comment by danwos** [comment] 2021-09-09 09:39
I was able to understand the trigger of the problem now.
 It is not Sphinx-Needs specific, but somehow related to the content of a config value.
 
**Problem**: Files get processed and written again, if a config-option in ``conf.py`` has a function assigned.

## Test code
Run the test twice, if a change happened in ``conf.py``.
The second run should use incremental build and do not rewrite rst files.

```python
# conf.py

def setup(app):
    app.add_config_value("test_option", None, "html")

import os  # used to represent a module assignment

def test_func():
    pass

class test_class:
    pass

# Use only one example of the below in a test

test_option = "string"  # all good
test_option = test_class  # all good

test_option = test_func  # no incremental build

test_ option = os  # all_good
test_option = os.path.isdir  # no incremental build

```

## Workaround for Sphinx-Needs
As ``needs_extra_options`` always needs ``directives.unchanged``, we could remove the need to assign it in ``conf.py`` and set it automatically .

However, there are other options, which support setting a function.
E.g for calculating warnings or dynamic functions.

I have not tested it, but I'm pretty sure that the usage of these will trigger the problem again and I see no workaround for them.

## Next steps
I will open a Bug-Report on Sphinx main project.

**Comment by danwos** [comment] 2021-09-09 10:20
Bug report created: https://github.com/sphinx-doc/sphinx/issues/9622

**Comment by twodrops** [comment] 2021-09-09 13:51
Wow! That's really something that you found out here. I 100% believe that it is no easy to nail such problems down.

I guess, for sphinx, any change in conf.py is triggering a full write build. With a function returning a value in conf.py, sphinx perhaps is not checking if the result of a function remained the same between two calls/builds. They should have some kind of a hash for a "resolved" conf.py.

> However, there are other options, which support setting a function.
E.g for calculating warnings or dynamic functions.

You are right. As I wrote in my initial bug report, I observed it for dynamic functions as well. I guess it does not make sense to fix it for `needs_extra_options` alone with the solution you mentioned. Irrespective of this issue, it might still be a good option to set `directives.unchanged` from code, to keep the declarations shorter in `conf.py`

I am interested to see what sphinx team says about this.

**Comment by danwos** [comment] 2021-09-09 15:54
Yeah, was not a pleasure to hunt this bug. Deactivated a lot of sphinx-needs code to figure out what triggers this bug.
But after really everything was deactivated, only Sphinx itself could be the source. After knowing this it became quite easy to test :)

However, a function which gets executed in ``conf.py`` works, e.g. ``test_option = test_func()``!
Only when the function object itself is assigned, the problem happens.

I have also made some further tests and set the value of ``test_option`` in different sphinx events.
When change happens in event ``config_inited``, incremental build does not work.
Changes in later events works as a charm.  
I have updated the sphinx-issue with more details about this.

**Comment by danwos** [comment] 2021-09-09 21:16
Okay, the behaviour makes sense and can not be solved by sphinx in a safe way. See linked issue for details.

But there are two solutions, which I will test:
1) a string, which defines an importable function, so that the function can be imported and assigned during runtime
2) an API call to register such functions directly in a setup(app) function of conf.py.

Not sure, which one is better for the user and also produces less problems.

**Comment by danwos** [comment] 2021-09-10 06:23
I have decided to go with solution 2). Provide an API for function assignment in configuration.
This allows us to have more control and it can have multiple arguments, which makes it more flexible.
The new API can then also be used by  Sphinx-Needs extensions.

The string solution is not so easy to implement, as e.g. for warnings a string can also be a filter-string. So not so easy to detect, for what a given string shall be used for.

So a solution may look like:
```python
# conf.py

from sphinxcontrib.needs import api

def  my_warning_func():
    pass
    
# some other user specific functions

def setup(app):
    api.register warning_func("name", my_warning_func)
    api.register_dynamicv_func("name", my_dyn_func)

needs_extra_options = [
    'author',
    'another_option'
]
```

For ``needs_extra_options`` I would remove the need to add ``directives.unchanged``.
I think for this we do not need an API (at least to solve the problem in this issue).

Assigning functions for the related config options will still be possible.
So it is backwards compatible.
But I will add a config-check, which prints some hints, if this "old" way is used and incremental build gets deactivated.

The API-way may be also a solution for some other issues (e.g. the general option model). Let see :)

**Comment by twodrops** [comment] 2021-10-01 11:49
@danwos As a first step of testing this fix, I changed ```needs_extra_options``` in ```conf.py``` as follows:

Before:
```
# need option definitions
from docutils.parsers.rst import directives   
needs_extra_options = {
"asil": directives.unchanged,
"version": directives.unchanged,
"impacts": directives.unchanged
}
```

After:
```
needs_extra_options = [
    "asil",
    "version",
    "impacts"
]
```

With the master branch, it throws the following exception. 
```
Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/sphinxcontrib/needs/directives/need.py", line 84, in run
    for extra_option in env.config.needs_extra_options.keys():
AttributeError: 'list' object has no attribute 'keys'
```

Looks like a dict is still expected. Any clue on this?

**Comment by twodrops** [comment] 2021-10-04 08:40
The key seems to be fetched here
https://github.com/useblocks/sphinxcontrib-needs/blob/4361575876f3827040dccffc1969a55c6fcdff04/sphinxcontrib/needs/directives/need.py#L84

**Comment by twodrops** [comment] 2021-10-04 11:16
Another question:
`
To register dynamic functions the following code looks fine
```
add_dynamic_function(app, my_dynamic_function)
```
To register a custom warning, why the additional ``id`` needs to be passed to `add_warning`
```
add_warning(app, 'my_warning', my_custom_warning)
```

**Comment by danwos** [comment] 2021-10-04 11:32
The ``id`` for ``addwarning`` is more a name for the warning, which gets printed when the warning is checked.
In old way the ``id`` was the key of the dict.

It is important to have this, so that Sphinx-Needs can print a maybe meaningful name for a complex filter string.

**Comment by twodrops** [comment] 2021-10-04 11:47
Yes, this I understand. I was wondering why the new registration function cannot be similar to the dynamic function registration
For example,
```
add_warning(app, my_custom_warning)
```
That is, avoid ``ìd`` as parameter here during registration.

**Comment by danwos** [comment] 2021-10-05 07:39
In your case the warning would have no name/id, which tells the user some details about it (on stdout).
In this case Sphinx-Needs could take automatically the function-name as name/id.
But for filter string, we would still need a name/id.
So to keep it simple, I would say all types of warnings must always get name/id given by user.

For dynamic_function we don't need a name/id, as there we take the name from the function.

So this is not really a question of how the warnings API is designed, but more how warnings are internally implemented (name + filter string/function)

**Comment by twodrops** [comment] 2021-10-05 08:04
I am a bit confused here (because of my lack of understanding the new registration functions in setup())

The information on 'id' and 'name' is available through the dictionary below.

```
needs_warnings = {
'my_warning': my_custom_warning
}
```

I was wondering if the duplication of the id could be avoided at two places (in ```add_warning``` and in ```needs_warnings```).

As I now understand, the 'id' is required at the early stage of initialization (in setup()) and cannot be reused from the dictionary declared later. Is this right?

**Comment by danwos** [comment] 2021-10-05 08:10
If you use the API registration in ``setup()``, you don't need any other configuration.
So ``needs_warnings`` is not needed.

You can still use it to register warnings based on filter strings (or register them also via api-call).

``needs_warnings`` gets later merged by Sphinx-Needs with the warnings coming from API calls (e.g. per ``setup()`` or external extensions).
But defining warnings twice, should throw an exception, as the "name/id" for a warning got already registered.

So ``needs_warnings`` and ``add_warning()`` are doing somehow the same thing, but are not based on each other and the used name/id should be used by one of them only.

**Comment by twodrops** [comment] 2021-10-05 08:21
ah got it.

I thought ```add_warning()``` is additional to ```needs_warnings```.  The example here also uses both together https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#incremental-build-support

I did not get any warning when I used both together. It simply worked.

This means, ```needs_functions``` is also not needed when ```add_dynamic_function``` is used, right?

**Comment by danwos** [comment] 2021-10-05 08:24
Ohh thanks for the hint with the documentation.
The used names there should not be the same....
Will fix it soon.

And right ``needs_functions`` is not needed when ``add_dynamic_function`` is used.

I will also add some additional tests, to safely check if things got registered twice.

**Comment by danwos** [comment] 2021-10-05 11:05
Fixed the found bugs.
Also !"double registration" is not printing a warning.

**Closed** 2021-10-05 11:04 UTC

**Comment by twodrops** [comment] 2021-10-05 12:07
Thanks for the fix.

With the latest fix, I get a different warning:

```WARNING: The config value `needs_extra_options' has type `list', defaults to `dict'.```

My  ```needs_extra_options``` looks similar to below:

```
needs_extra_options = [
"asil",
"version",
"impacts",
"relates"
]
```

**Comment by danwos** [comment] 2021-10-05 13:26
This warning is coming from Sphinx, telling you that the default type of needs_extra_options is a dict, because dict was supported first by Sphinx-Needs.

The change allows to set ``needs_extra_options`` now to list or dict. But for sure there can be only one default and its type.
I will change it to a list, as I think this should be the common configuration type from now on.

Will also add an additional hint from Sphinx-Needs that with 0.7.2 "list" is the way to go.

**Comment by twodrops** [comment] 2021-10-05 14:50
Cool, I can confirm that the incremental build works again with sphinx-needs!
If the above reported warning is removed as well, then my build will be green too :) (as my sphinx reports all warnings as errors).

I will do some detailed testing soon.
