### ISSUE TITLE
Needs collapse does not work anymore

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#242] opened 2021-04-22 08:07 UTC
The collapse/expand seems to be broken on master
![2021-04-22_10h03_59](https://user-images.githubusercontent.com/103930/115679137-880aff80-a352-11eb-8f73-404d7c250e47.png)

**Comment by twodrops** [comment] 2021-04-23 13:46
@danwos Thanks for fixing this before the 0.6.1 release

**Comment by twodrops** [comment] 2021-04-25 11:29
@danwos I thought it worked for me on master at some point. Now it doesn't work for me on master or with 0.6.1 release. The collapse appears as in the screenshot above

**Comment by danwos** [comment] 2021-04-25 13:04
It works with the official docs.

What kind of theme do you use?
Can you switch to "alabaster" for a quick test?

**Comment by twodrops** [comment] 2021-04-25 13:28
Yes, I did test with Alabaster and RTD. Not sure what I am doing wrong :(
 
I will create a new conf.py with defaults and test again.

**Comment by twodrops** [comment] 2021-04-25 14:54
I tried everything possible, but still the same behavior :(
I have the absolute minimum conf.py and my pip says the following:
`sphinxcontrib-needs==0.6.1`

**Comment by danwos** [comment] 2021-04-25 15:31
Just tested it also with a fresh new venv and project. And it looks good.

Maybe a browser cach problem on your side?
I have this sometimes and I need to open the browser-dev-tools (F12) so that no caches are used.

**Comment by twodrops** [comment] 2021-04-25 16:13
Tried that too and different browsers.

Looks like the css and js are not present in the build folder.
![2021-04-25_18h09_27](https://user-images.githubusercontent.com/103930/116000759-ce31be80-a5f1-11eb-8767-18fa463ac85b.png)
The only file present in the `../libs/html folder` is `datatables_loader.js`
I did clear the build folder and try.

**Comment by twodrops** [comment] 2021-04-26 17:33
@danwos Anyone clue why the files are not copied? I confirmed that I have the correct version with the #247 fix.

**Comment by danwos** [comment] 2021-04-26 17:40
Ohh sh**
Maybe I have make a stupid  mistake and have hard coded the the path separator "/".
This would not work on windows.....
Need to check this.

Reopen this issue.

**Comment by twodrops** [comment] 2021-04-26 17:46
No issues :) 
I am in a Linux Docker container. So I doubt if it is a path problem, but worth checking

**Comment by danwos** [comment] 2021-04-28 13:12
This problem is caused by #252, which is a more generic issue with copied static files.
Development will be done in #252.

So I close this issue again.

**Closed by danwos** 2021-04-28 13:12 UTC
