### ISSUE TITLE
I cannot build the examples from a clean environment

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinxcontrib-needs#436] opened 2021-12-02 20:10 UTC
Hi,
I try to build one of the examples with a new PC.
It is a windows 10 machine, anaconda feshly installed.

I downloaded the last tagge version of sphinxcontrib-needs from github (0.7.4).

Then I run:
`sphinx-build sphinxcontrib-needs-0.7.4\docs _build`
I get always:
```
Extension error (sphinx_data_viewer.sphinx_data_viewer):
Handler <function install_lib_static_files at 0x00000211E4E24B80> for event 'env-updated' threw an exception (exception: [Errno 2] No such file or directory: 'C:\\z\\_build\\_static\\assets/jsonview.bundle.js')
```

What I wonder here is: the folder is empty, so why does the tool expect some files?

Here are the comandes copied from cli:
```
(base) PS C:\Users\Admin> cd ..
(base) PS C:\Users> cd ..
(base) PS C:\> cd z
(base) PS C:\z> pip install sphinxcontrib-needs
Collecting sphinxcontrib-needs
  Downloading sphinxcontrib-needs-0.7.4.tar.gz (2.3 MB)
     |████████████████████████████████| 2.3 MB 6.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting requests-file<2.0.0,>=1.5.1
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: jsonschema==3.2.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinxcontrib-needs) (3.2.0)
Requirement already satisfied: sphinx>2.2 in c:\users\admin\anaconda3\lib\site-packages (from sphinxcontrib-needs) (4.2.0)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in c:\users\admin\anaconda3\lib\site-packages (from sphinxcontrib-needs) (2.26.0)
Requirement already satisfied: matplotlib>3.1.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinxcontrib-needs) (3.4.3)
Collecting sphinxcontrib-programoutput<0.18,>=0.17
  Downloading sphinxcontrib_programoutput-0.17-py2.py3-none-any.whl (22 kB)
Collecting sphinx-data-viewer<0.2.0,>=0.1.1
  Downloading sphinx-data-viewer-0.1.1.tar.gz (6.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting sphinxcontrib-plantuml<0.22,>=0.21
  Downloading sphinxcontrib-plantuml-0.21.tar.gz (11 kB)
Collecting sphinx-panels<0.7.0,>=0.6.0
  Downloading sphinx_panels-0.6.0-py3-none-any.whl (87 kB)
     |████████████████████████████████| 87 kB 3.3 MB/s
Collecting sphinx-copybutton<0.4.0,>=0.3.0
  Downloading sphinx_copybutton-0.3.3-py3-none-any.whl (12 kB)
Requirement already satisfied: attrs>=17.4.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema==3.2.0->sphinxcontrib-needs) (21.2.0)
Requirement already satisfied: setuptools in c:\users\admin\anaconda3\lib\site-packages (from jsonschema==3.2.0->sphinxcontrib-needs) (58.0.4)
Requirement already satisfied: six>=1.11.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema==3.2.0->sphinxcontrib-needs) (1.16.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema==3.2.0->sphinxcontrib-needs) (0.18.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib>3.1.0->sphinxcontrib-needs) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib>3.1.0->sphinxcontrib-needs) (1.3.1)
Requirement already satisfied: numpy>=1.16 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib>3.1.0->sphinxcontrib-needs) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib>3.1.0->sphinxcontrib-needs) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib>3.1.0->sphinxcontrib-needs) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib>3.1.0->sphinxcontrib-needs) (8.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests<3.0.0,>=2.25.1->sphinxcontrib-needs) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests<3.0.0,>=2.25.1->sphinxcontrib-needs) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests<3.0.0,>=2.25.1->sphinxcontrib-needs) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from requests<3.0.0,>=2.25.1->sphinxcontrib-needs) (2.0.4)
Requirement already satisfied: sphinxcontrib-applehelp in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (1.1.5)
Requirement already satisfied: sphinxcontrib-qthelp in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (1.0.3)
Requirement already satisfied: Jinja2>=2.3 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (2.11.3)
Requirement already satisfied: Pygments>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (2.10.0)
Requirement already satisfied: docutils<0.18,>=0.14 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (0.17.1)
Requirement already satisfied: snowballstemmer>=1.1 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (2.1.0)
Requirement already satisfied: babel>=1.3 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (2.9.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (0.7.12)
Requirement already satisfied: imagesize in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (1.2.0)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (21.0)
Requirement already satisfied: colorama>=0.3.5 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>2.2->sphinxcontrib-needs) (0.4.4)
Requirement already satisfied: pytz>=2015.7 in c:\users\admin\anaconda3\lib\site-packages (from babel>=1.3->sphinx>2.2->sphinxcontrib-needs) (2021.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\admin\anaconda3\lib\site-packages (from Jinja2>=2.3->sphinx>2.2->sphinxcontrib-needs) (1.1.1)
Building wheels for collected packages: sphinxcontrib-needs, sphinx-data-viewer, sphinxcontrib-plantuml
  Building wheel for sphinxcontrib-needs (PEP 517) ... done
  Created wheel for sphinxcontrib-needs: filename=sphinxcontrib_needs-0.7.4-py3-none-any.whl size=2571201 sha256=37fa8964bfe395303f4fbe87c6139cd63a13b2bf57a7170bec30ba70a4788e33
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\3f\d1\89\f59b85728a698142d3b65a68022ad760e42fcc68b3648937a3
  Building wheel for sphinx-data-viewer (PEP 517) ... done
  Created wheel for sphinx-data-viewer: filename=sphinx_data_viewer-0.1.1-py3-none-any.whl size=7913 sha256=f851b8ae58e4dd9ca10ef6cbf7e5395a22391037444487a7e25888af2443fd5f
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\b8\b1\be\12df22dc5eba4e3ee14cfcca8d5d5628a80c75405993dcb0a9
  Building wheel for sphinxcontrib-plantuml (setup.py) ... done
  Created wheel for sphinxcontrib-plantuml: filename=sphinxcontrib_plantuml-0.21-py3-none-any.whl size=10435 sha256=3a03d115f9b37c4a01c3d487d5005b129462cb8f661a5311fd71aadd52741b39
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\1f\36\5a\68688bca21e00b5841e58650bf1a373ae229032affc8b34e4f
Successfully built sphinxcontrib-needs sphinx-data-viewer sphinxcontrib-plantuml
Installing collected packages: sphinxcontrib-programoutput, sphinxcontrib-plantuml, sphinx-panels, sphinx-data-viewer, sphinx-copybutton, requests-file, sphinxcontrib-needs
Successfully installed requests-file-1.5.1 sphinx-copybutton-0.3.3 sphinx-data-viewer-0.1.1 sphinx-panels-0.6.0 sphinxcontrib-needs-0.7.4 sphinxcontrib-plantuml-0.21 sphinxcontrib-programoutput-0.17
(base) PS C:\z> cd .\sphinxcontrib-needs-0.7.4\
(base) PS C:\z\sphinxcontrib-needs-0.7.4> cd .\docs\
(base) PS C:\z\sphinxcontrib-needs-0.7.4\docs> pip install -r requirements.txt
Requirement already satisfied: sphinx>=3.4 in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (4.2.0)
Requirement already satisfied: sphinxcontrib-plantuml in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (0.21)
Requirement already satisfied: matplotlib in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (3.4.3)
Requirement already satisfied: sphinx-copybutton in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 4)) (0.3.3)
Requirement already satisfied: sphinxcontrib-programoutput in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 5)) (0.17)
Requirement already satisfied: sphinx-panels in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 6)) (0.6.0)
Requirement already satisfied: click in c:\users\admin\anaconda3\lib\site-packages (from -r requirements.txt (line 8)) (8.0.3)
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Requirement already satisfied: sphinxcontrib-applehelp in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (1.1.5)
Requirement already satisfied: sphinxcontrib-qthelp in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (1.0.3)
Requirement already satisfied: Jinja2>=2.3 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (2.11.3)
Requirement already satisfied: Pygments>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (2.10.0)
Requirement already satisfied: docutils<0.18,>=0.14 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (0.17.1)
Requirement already satisfied: snowballstemmer>=1.1 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: babel>=1.3 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (2.9.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (0.7.12)
Requirement already satisfied: imagesize in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: requests>=2.5.0 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: setuptools in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (58.0.4)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (21.0)
Requirement already satisfied: colorama>=0.3.5 in c:\users\admin\anaconda3\lib\site-packages (from sphinx>=3.4->-r requirements.txt (line 1)) (0.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: numpy>=1.16 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.20.3)
Requirement already satisfied: pytz>=2015.7 in c:\users\admin\anaconda3\lib\site-packages (from babel>=1.3->sphinx>=3.4->-r requirements.txt (line 1)) (2021.3)
Requirement already satisfied: six in c:\users\admin\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\admin\anaconda3\lib\site-packages (from Jinja2>=2.3->sphinx>=3.4->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.5.0->sphinx>=3.4->-r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.5.0->sphinx>=3.4->-r requirements.txt (line 1)) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.5.0->sphinx>=3.4->-r requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.5.0->sphinx>=3.4->-r requirements.txt (line 1)) (1.26.7)
Installing collected packages: tabulate
Successfully installed tabulate-0.8.9
(base) PS C:\z\sphinxcontrib-needs-0.7.4\docs> cd ..
(base) PS C:\z\sphinxcontrib-needs-0.7.4> cd ..
(base) PS C:\z> sphinx-build sphinxcontrib-needs-0.7.4\docs _build
Running Sphinx v4.2.0
GITHUB: No auth provided
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 29 source files that are out of date
updating environment: [new config] 29 added, 0 changed, 0 removed
Service github-issues requesting data for query: repo:useblocks/sphinxcontrib-needs node latexpdf is:issue
Service github-issues requesting data for query: repo:useblocks/sphinxcontrib-needs node latexpdf is:issue
Service github-issues requesting data for query: repo:useblocks/sphinxcontrib-needs node latexpdf is:issue
Service github-issues requesting data for query: repo:useblocks/sphinxcontrib-needs state:open needtable viewports is:issue
Service github-prs requesting data for query: useblocks/sphinxcontrib-needs/161
Service github-issues requesting data for query: repo:useblocks/sphinxcontrib-needs node latexpdf is:issue
Service github-commits requesting data for query: repo:useblocks/sphinxcontrib-needs python
Service github-commits requesting data for query: useblocks/sphinxcontrib-needs/a4a596113
reading sources... [100%] support
C:\z\sphinxcontrib-needs-0.7.4\docs\contributing.rst:60: WARNING: Command ['make', '--no-print-directory', '--directory', '../', 'list'] failed: [WinError 2] Das System kann die angegebene Datei nicht finden
WARNING: Scruffy tag definition found in need GH_166. Defined tag contains spaces only.

====================== slowest reading durations =======================
38.518 performance
1.772 services/github
0.468 api
0.464 directives/needservice
0.296 changelog

Extension error (sphinx_data_viewer.sphinx_data_viewer):
Handler <function install_lib_static_files at 0x0000019132E56E50> for event 'env-updated' threw an exception (exception: [Errno 2] No such file or directory: 'C:\\z\\_build\\_static\\assets/jsonview.bundle.js')
```

I tried secoundly to have only a minimu rst file. So I setup a minium project (took over C:\z\sphinxcontrib-needs-0.7.4\docs\examples\index.rst and conf.py).
But I get the same error.

```
(base) PS C:\z> cd docs
(base) PS C:\z\docs> dir


    Verzeichnis: C:\z\docs


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        02.12.2021     20:39                utils
d-----        02.12.2021     20:51                _images
d-----        02.12.2021     20:39                _static
-a----        30.11.2021     16:16          15184 conf.py
-a----        30.11.2021     16:16           4037 index.rst


(base) PS C:\z\docs> cd ..
(base) PS C:\z> sphinx-build docs _build
Running Sphinx v4.2.0
GITHUB: No auth provided
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index

====================== slowest reading durations =======================
0.046 index

Extension error (sphinx_data_viewer.sphinx_data_viewer):
Handler <function install_lib_static_files at 0x0000024A61985B80> for event 'env-updated' threw an exception (exception: [Errno 2] No such file or directory: 'C:\\z\\_build\\_static\\assets/jsonview.bundle.js')
```

**Comment by danwos** [comment] 2021-12-02 20:18
Thanks for the really detailed report.

The problem is in the used dependency Sphinx-Data-Viewer, which is quite a new extension (also developed by me).
And I just detected, that my folder handling is not so clean and 1-2 paths are containing a hard-coded "/", but windows would need a "\\".

That's the reason for the strange path ``C:\\z\\_build\\_static\\assets/jsonview.bundle.js``.

I will fix it tomorrow and release a new version.
Sorry for the problem and I hope you will test it again for me, as I have no direct access to a windows machine :)

**Comment by PhilipPartsch** [comment] 2021-12-02 20:30
For sure I will do.

**Comment by danwos** [comment] 2021-12-09 07:20
Closed this, as it is based on https://github.com/useblocks/sphinx-data-viewer/issues/2, which got solved.

**Closed by danwos** 2021-12-09 07:20 UTC
